/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brunocalou_guitarstudio_AudioProcessor */

#ifndef _Included_com_brunocalou_guitarstudio_AudioProcessor
#define _Included_com_brunocalou_guitarstudio_AudioProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brunocalou_guitarstudio_AudioProcessor
 * Method:    startProcess
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_brunocalou_guitarstudio_AudioProcessor_startProcess
  (JNIEnv *, jobject);

/*
 * Class:     com_brunocalou_guitarstudio_AudioProcessor
 * Method:    stopProcess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_brunocalou_guitarstudio_AudioProcessor_stopProcess
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
