/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brunocalou_guitarstudio_Effect */

#ifndef _Included_com_brunocalou_guitarstudio_Effect
#define _Included_com_brunocalou_guitarstudio_Effect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brunocalou_guitarstudio_Effect
 * Method:    _initNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brunocalou_guitarstudio_Effect__1initNative
  (JNIEnv *, jobject);

/*
 * Class:     com_brunocalou_guitarstudio_Effect
 * Method:    _destroyNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brunocalou_guitarstudio_Effect__1destroyNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brunocalou_guitarstudio_Effect
 * Method:    _enable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brunocalou_guitarstudio_Effect__1enable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brunocalou_guitarstudio_Effect
 * Method:    _disable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brunocalou_guitarstudio_Effect__1disable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brunocalou_guitarstudio_Effect
 * Method:    _setLevel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_brunocalou_guitarstudio_Effect__1setLevel
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
