/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brunocalou_guitarstudio_DistortionEffect */

#ifndef _Included_com_brunocalou_guitarstudio_DistortionEffect
#define _Included_com_brunocalou_guitarstudio_DistortionEffect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brunocalou_guitarstudio_DistortionEffect
 * Method:    _setThreshold
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_brunocalou_guitarstudio_DistortionEffect__1setThreshold
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_brunocalou_guitarstudio_DistortionEffect
 * Method:    _initNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brunocalou_guitarstudio_DistortionEffect__1initNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
